#Face Expression Client settings
#Sun May 17 17:45:58 CEST 2026
calibration.expression=Neutral
camera.index=0
facetrack.landmark.model=models/lbfmodel.yaml
facetrack.onnx.model=models/fan2_68_landmark.onnx
hardware.acceleration=OPENCL
microphone.amplificationPercent=197
microphone.device=alsa_playback.java [default]|ALSA (http\://www.alsa-project.org)|6.14.0-1008-intel
microphone.sensitivityPercent=100
microphone.speech.enabled=true
offaxis.holdMillis=0
offaxis.minFrontalQualityPercent=0
offaxis.mode=HOLD_LAST
opencv.threads=8
profile.name=default
recognition.quality=ACCURATE
tracker.backend=MODERN_ONNX
version=1
window.height=1158
window.maximized=false
window.width=1811
window.x=75
window.y=253
