#Face Expression Client calibration profile
#Sun May 17 17:31:54 CEST 2026
baseline.openScore=1.00000000
baseline.sadScore=0.86890147
baseline.samples=45
baseline.smileScore=0.00000000
baseline.targetFrames=45
baseline.wideScore=0.00000000
profile.cameraIndex=0
profile.name=default
profile.quality=BALANCED
version=2
