#Face Expression Client calibration profile
#Sat May 16 23:07:46 CEST 2026
baseline.openScore=0.18157719
baseline.sadScore=0.26566459
baseline.samples=45
baseline.smileScore=0.60288015
baseline.targetFrames=45
baseline.wideScore=0.00000000
expression.neutral.blinkShapeScore=0.00000000
expression.neutral.bothEyesScore=0.73333333
expression.neutral.browFurrowScore=0.00000000
expression.neutral.browRaiseScore=0.00000000
expression.neutral.expressionScore=0.20458490
expression.neutral.headYawScore=0.00000000
expression.neutral.mouthActivityScore=0.75145475
expression.neutral.noEyesScore=0.00000000
expression.neutral.oneEyeScore=0.26666667
expression.neutral.openScore=0.21499265
expression.neutral.sadScore=0.25409199
expression.neutral.samples=45
expression.neutral.smileScore=0.23620325
expression.neutral.targetFrames=45
expression.neutral.wideScore=0.00000000
expression.neutral.winkShapeScore=0.17709424
profile.cameraIndex=0
profile.name=default
profile.quality=FAST
version=2
