#Face Expression Client calibration profile
#Fri May 15 18:50:09 CEST 2026
baseline.openScore=0.00000000
baseline.sadScore=0.42602292
baseline.samples=60
baseline.smileScore=0.38184558
baseline.targetFrames=60
baseline.wideScore=0.00000000
expression.blinking.bothEyesScore=0.20000000
expression.blinking.expressionScore=0.08300000
expression.blinking.mouthActivityScore=0.19769261
expression.blinking.noEyesScore=0.16666667
expression.blinking.oneEyeScore=0.63333333
expression.blinking.openScore=0.02677139
expression.blinking.sadScore=0.00000000
expression.blinking.samples=60
expression.blinking.smileScore=0.02603107
expression.blinking.targetFrames=60
expression.blinking.wideScore=0.00000000
expression.focused.bothEyesScore=0.93333333
expression.focused.expressionScore=0.24986185
expression.focused.mouthActivityScore=0.00000000
expression.focused.noEyesScore=0.03333333
expression.focused.oneEyeScore=0.03333333
expression.focused.openScore=0.00000000
expression.focused.sadScore=0.66620950
expression.focused.samples=60
expression.focused.smileScore=0.35047302
expression.focused.targetFrames=60
expression.focused.wideScore=0.00000000
expression.happy.bothEyesScore=0.56666667
expression.happy.expressionScore=0.82164271
expression.happy.mouthActivityScore=0.00000000
expression.happy.noEyesScore=0.26666667
expression.happy.oneEyeScore=0.16666667
expression.happy.openScore=0.00000000
expression.happy.sadScore=0.81144220
expression.happy.samples=60
expression.happy.smileScore=0.97698413
expression.happy.targetFrames=60
expression.happy.wideScore=0.00000000
expression.neutral.bothEyesScore=0.91666667
expression.neutral.expressionScore=0.53200940
expression.neutral.mouthActivityScore=0.00000000
expression.neutral.noEyesScore=0.00000000
expression.neutral.oneEyeScore=0.08333333
expression.neutral.openScore=0.00000000
expression.neutral.sadScore=0.52386950
expression.neutral.samples=60
expression.neutral.smileScore=0.15075523
expression.neutral.targetFrames=60
expression.neutral.wideScore=0.00000000
expression.sad.bothEyesScore=0.90000000
expression.sad.expressionScore=0.72865196
expression.sad.mouthActivityScore=0.00000000
expression.sad.noEyesScore=0.00000000
expression.sad.oneEyeScore=0.10000000
expression.sad.openScore=0.00000000
expression.sad.sadScore=0.65330844
expression.sad.samples=60
expression.sad.smileScore=0.19682104
expression.sad.targetFrames=60
expression.sad.wideScore=0.00000000
expression.surprised.bothEyesScore=0.98333333
expression.surprised.expressionScore=0.10683272
expression.surprised.mouthActivityScore=0.00000000
expression.surprised.noEyesScore=0.00000000
expression.surprised.oneEyeScore=0.01666667
expression.surprised.openScore=0.00000000
expression.surprised.sadScore=0.13425036
expression.surprised.samples=60
expression.surprised.smileScore=0.07227116
expression.surprised.targetFrames=60
expression.surprised.wideScore=0.00000000
expression.talking.bothEyesScore=0.98333333
expression.talking.expressionScore=0.69337112
expression.talking.mouthActivityScore=0.96538659
expression.talking.noEyesScore=0.00000000
expression.talking.oneEyeScore=0.01666667
expression.talking.openScore=0.23051370
expression.talking.sadScore=0.95457204
expression.talking.samples=60
expression.talking.smileScore=0.40070129
expression.talking.targetFrames=60
expression.talking.wideScore=0.00000000
expression.winking.bothEyesScore=0.10000000
expression.winking.expressionScore=0.00000000
expression.winking.mouthActivityScore=0.00000000
expression.winking.noEyesScore=0.65000000
expression.winking.oneEyeScore=0.25000000
expression.winking.openScore=0.00000000
expression.winking.sadScore=0.85904510
expression.winking.samples=60
expression.winking.smileScore=0.28585615
expression.winking.targetFrames=60
expression.winking.wideScore=0.00000000
version=1
